plugin-svn/che-plugin-svn-ext-subversion/src/main/resources/org/eclipse/che/ide/ext/svn/client/subversion.css
This is ignored by the CSS compiler and generates a warning
=> Remove @CHARSET declaration

plugin-github/che-plugin-github-ext-github/src/main/java/org/eclipse/che/ide/ext/github/server/GitHubKeyUploader.java
Fixed: User can not import a project if ssh keys on git hub side more then 60.
=> IDEX-1177. Fixed: User can not import a project if ssh keys on git hub side more then 60.

plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/server/nativegit/NativeGitStatusImpl.java, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/server/nativegit/StatusTest.java
Incorrect behavior in current impl that was fixed:
- doesn't catch conflicting files that are deleted 
- doesn't catch 'added' files if they are later deleted
- adds 'missing' files as 'removed'
Aligning with standard documentation:
http://git-scm.com/docs/git-status#_short_format
Signed-off-by: Tareq Sharafy <tareq.sharafy@sap.com>
=> Align the native git status lists with standard git

plugin-sdk/che-plugin-sdk-runner/src/main/resources/codenvyPlatform/pom.xml, plugin-sdk/che-plugin-sdk-runner/src/main/resources/codenvyPlatform/src/main/webapp/WEB-INF/web.xml
Fixed: WebSocket is unavailable for extensions on Che.
=> IDEX-2765. Fixed: WebSocket is unavailable for extensions on Che.

plugin-docker/che-plugin-docker-client/src/main/java/org/eclipse/che/plugin/docker/client/json/HostConfig.java, plugin-docker/che-plugin-docker-runner/src/main/java/org/eclipse/che/plugin/docker/runner/BaseDockerRunner.java
From https://docs.docker.com/reference/api/docker_remote_api_v1.20/
to
https://docs.docker.com/reference/api/docker_remote_api_v1.14/
at least
=> IDEX-3099 Memory is not a string but long in hostconfig

plugin-sdk/che-plugin-sdk-runner/src/main/resources/codenvyPlatform/src/main/webapp/IDE.jsp
This is the text that appears in the browser tab when che is loading.
=> Fix <title> text to say Eclipse Che

plugin-docker/che-plugin-docker-client/src/main/java/org/eclipse/che/plugin/docker/client/DockerConnector.java, plugin-docker/che-plugin-docker-client/src/main/java/org/eclipse/che/plugin/docker/client/DockerConnectorConfiguration.java, plugin-docker/che-plugin-docker-client/src/main/java/org/eclipse/che/plugin/docker/client/helper/DefaultNetworkFinder.java, plugin-docker/che-plugin-docker-client/src/main/java/org/eclipse/che/plugin/docker/client/helper/NetworkFinder.java, plugin-docker/che-plugin-docker-client/src/test/java/org/eclipse/che/plugin/docker/client/DockerConnectorConfigurationTest.java, plugin-docker/che-plugin-docker-client/src/test/java/org/eclipse/che/plugin/docker/client/DockerConnectorTest.java, plugin-docker/che-plugin-docker-client/src/test/java/org/eclipse/che/plugin/docker/client/helper/DefaultNetworkFinderHelper.java, plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/DockerInstanceProvider.java, plugin-docker/che-plugin-docker-machine/src/test/java/org/eclipse/che/plugin/docker/machine/DockerInstanceProviderTest.java
And then add this container host as an extra host when starting a container
Change-Id: I953539a7a29e257d89a6604bfe9efb885965e508
=> IDEX-3244 Allow to detect the ip to use for the container host.

plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/delete/DeleteRepositoryPresenter.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/init/InitRepositoryPresenter.java, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/delete/DeleteRepositoryPresenterTest.java, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/init/InitRepositoryPresenterTest.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/project/interceptor/AbstractBeforeModuleOpenedInterceptor.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/project/interceptor/AbstractExternalLibrariesNodeInterceptor.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/project/interceptor/AbstractJavaContentRootInterceptor.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/project/interceptor/JavaClassInterceptor.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/project/node/PackageNode.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/project/node/SourceFolderNode.java, plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/client/project/PomNodeInterceptor.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/MachineComponent.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/command/valueproviders/CurrentProjectPathProvider.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/machine/MachineManager.java, plugin-machine/che-plugin-machine-ext-client/src/test/java/org/eclipse/che/ide/extension/machine/client/command/valueproviders/CurrentProjectPathProviderTest.java
Tree changes:
- in node renderer changed manipulations with html, now work performs with dom nodes
- added possibility to customize node styles directly from node by css
- added method to refresh visual representation of specified node without reloading
- temporary disable inner checking for child in child, to proper rendering ">" symbol
- fixed setting parent after node intercepting, in some cases few nodes was without parent
- updated mechanism of firing changing selection node event
Upgraded behaviour when expanded node renames. Now expanded nodes saves their state
In some cases directory structure may be changed if renamed directory becomes source directory
Machie's project path requests only when ide starts to avoid unneccessary requests during selection change
Get project method in …
=> IDEX-3049, IDEX-3319, IDEX-3449, IDEX-3450

plugin-docker/che-plugin-docker-client/src/main/java/org/eclipse/che/plugin/docker/client/DockerConnectorConfiguration.java
(see http://docs.docker.com/v1.8/articles/networking/) 
Change-Id: I6264bfcf93221a54f70079ff868cc4eccabcbd52
=> IDEX-3472 Use of Docker0 bridge name when we're on linux (bridge0 was not for Linux)

plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/server/SubversionApi.java
This is pull request issue https://jira.codenvycorp.com/browse/IDEX-3511
This pull request usages com.google.common.base.Strings instead of  org.eclipse.che.commons.lang.Strings.
=> IDEX-3511 : Remove usage deprecated class org.eclipse.che.commons.lang.Strings

plugin-github/che-plugin-github-ext-github/src/main/java/org/eclipse/che/ide/ext/github/server/GitHubDTOFactory.java, plugin-github/che-plugin-github-ext-github/src/main/java/org/eclipse/che/ide/ext/github/server/rest/GitHubService.java, plugin-github/che-plugin-github-ext-github/src/main/java/org/eclipse/che/ide/ext/github/shared/GitHubRepository.java, plugin-github/che-plugin-github-ext-github/src/main/java/org/kohsuke/github/CheGitHubClient.java, plugin-github/che-plugin-github-ext-github/src/main/java/org/kohsuke/github/GHRepositoryWithMirrorUrl.java
Will be used for warn user if the try contribute mirrored repository like https://github.com/apache/tomee.
Also create pull request to original lib https://github.com/kohsuke/github-api/pull/233
=> IDEX-3128: Add posibility to get mirror repository url.

plugin-git/che-plugin-git-ext-git/src/main/resources/org/eclipse/che/ide/ext/git/client/git.css
Fix warning message during gwt compiling 'Charset declaration detected.
A charset at-rule is not relevant inside a style element'
@vparfonov WDYT?
=> Remove CHARSET from git.css

plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/DockerInstanceKey.java, plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/DockerInstanceProvider.java, plugin-docker/che-plugin-docker-machine/src/test/java/org/eclipse/che/plugin/docker/machine/DockerInstanceProviderTest.java
Swarm has problems with scheduling containers if image id is used instead of repo. This PR fixes incorrect containers scheduling and allow system admin correlate docker image/container with workspace/machine
=> CLDIDE-2633 Use repo instead of image id in docker machine impl

plugin-orion/che-plugin-orion-editor/src/main/resources/org/eclipse/che/ide/editor/orion/public/orion-10.0/che/plugins/jsContentAssistPlugin.js
* fixed cursor positioning for custom suggestions in JS-editor (which was loaded from _proposals.json_);
* paramenter _overwrite_ in _proposals.json_ isn't use anymore: it will be always 'true';
* avoid using synchronous XMLHttpRequest - used Promises intsead;
* no need to reload the page for reloading the changes in _proposals.json_;
* added handling of errors of getting and parsing _proposals.json_.
=> IDEX-3636: fix cursor positioning for custom suggestions in JS-editor

plugin-sdk/che-plugin-sdk-env-local/src/main/java/org/eclipse/che/env/local/client/CheConnectionClosedInformer.java
Don't show popup when abnormal close code is gotten from websocket and reason is absent
=> Don't show popup when abnormal close code is gotten from websocket and reason is absent

plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/DockerInstance.java, plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/DockerInstanceProvider.java
Comment usage of container state change because it has bug.
Exec's OOM is treated as OOM of container.
=> IDEX-3744: disable docker machine state change detection

plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/command/edit/EditCommandsViewImpl.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/outputspanel/console/OutputConsoleViewImpl.ui.xml, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelPresenter.java, plugin-machine/che-plugin-machine-ext-client/src/main/resources/org/eclipse/che/ide/extension/machine/client/MachineLocalizationConstant.properties, plugin-machine/che-plugin-machine-ext-client/src/main/resources/org/eclipse/che/ide/extension/machine/client/machine.css, plugin-machine/che-plugin-machine-ext-client/src/test/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelPresenterTest.java
#1 - Fix displaying of Icon for the Consoles panel
#2 - Fix naming of terminals: Terminal-## instead of Terminal (##)
#3 - Number for terminals start with "Terminal" then the second one "Terminal-2" and then we go incrementaly
#4 - Add title "Consoles" for the panel
#5 - Change displaying of 'Add new terminal' icon
#6 - Remove bold for "command:" in the output view
=> IDEX-3817 Small fixes after review for console panel UI

plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/machine/panel/MachinePanelPresenter.java
We show the loader for dev machine when this one is starting 
So we shouldn't duplicate message in machine panel
=> IDEX-3632. Don't duplicate message about starting machine for dev macnine

plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/JavaLocalizationConstant.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/search/FindUsagesPresenter.java, plugin-java/che-plugin-java-ext-lang-client/src/main/resources/org/eclipse/che/ide/ext/java/client/JavaLocalizationConstant.properties
@vparfonov @ashumilova 
this need to visual identify tabs if we use find text and usages in the same time
=> IDEX-4039: Rename Find tab to Usages

plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/CurrentClassFQNProvider.java
Editor now has ability to provide into selection model current opened file. And Current class fqn provider now listen selection changed events to have ability provide fqn on selected file in Project Explorer or another place.
Screencast: https://slack-files.com/T02G3VAG4-F0JF7CB0T-650823b3be
Related PR: https://github.com/codenvy/che-core/pull/628
=> Add ability to configure selection with opened file in editor

plugin-sdk/che-plugin-sdk-ext-plugins/src/main/java/org/eclipse/che/ide/ext/plugins/client/PluginsLocalizationConstant.java, plugin-sdk/che-plugin-sdk-ext-plugins/src/main/java/org/eclipse/che/ide/ext/plugins/client/command/CommandPageViewImpl.ui.xml, plugin-sdk/che-plugin-sdk-ext-plugins/src/main/resources/org/eclipse/che/ide/ext/plugins/client/PluginsLocalizationConstant.properties
Several guys have asked me why they can't launch *GWT SDM for Che* command for just cloned projects. This is because their projects are not built yet.
Such warning may prevent user to be confused why *GWT SDM for Che* command doesn't work when projects aren't built yet.
@vparfonov
=> Notice user that projects must be built before launching GWT SDM for Che command

plugin-orion/che-plugin-orion-editor/pom.xml, plugin-orion/che-plugin-orion-editor/src/main/patches/Bug482536.diff, plugin-orion/che-plugin-orion-editor/src/main/patches/built-codeEdit-amd.js.diff
=> IDEX-4062: fix disabling IFRAME on opening an empty context menu in Orion editor (https://bugs.eclipse.org/bugs/show_bug.cgi?id=481940)

pom.xml
Removed unused property **maven.model.version** in pom.xml since we don't use **org.apache.maven.maven-model** anymore
@vparfonov
=> Remove unused property maven.model.version in pom.xml since we don't use org.apache.maven.maven-model anymore

plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/commit/CommitPresenter.java, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/commit/CommitPresenterTest.java
When performing git commit with "add selected files" check-box selected and console part is active, NPE appears because the getSelection method in Selection agent returned a selection of console part, but we need a selection of project explorer
@vparfonov @skabashnyuk  please review
=> IDEX-2389: Add getProjectExplorerSelection method in SelectionAgent

plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/editor/OpenDeclarationFinder.java, plugin-java/che-plugin-java-ext-lang-client/src/main/resources/org/eclipse/che/ide/ext/java/Java.gwt.xml, plugin-orion/che-plugin-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/OrionEditorWidget.java, plugin-orion/che-plugin-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/jso/OrionEditorOverlay.java, plugin-orion/che-plugin-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/jso/OrionInputChangedEventOverlay.java
Set cursor position only then content already added to editor but in some case we need a little timeout in OpenDeclarationFinder (set it to 100 ms)
@evidolob @azatsarynnyy
=> IDEX-3955:Use handler for catching event then content inject to Editor Widget

plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/outputconsole/GitOutputPartViewImpl.ui.xml, plugin-machine/che-plugin-machine-ext-client/src/main/resources/org/eclipse/che/ide/extension/machine/client/machine.css
Add padding for terminal panel and git console outputs
@slemeur
=> IDEX-4134. Add padding for terminal panel and git console outputs

plugin-java/che-plugin-java-ext-debugger-java-client/src/main/java/org/eclipse/che/ide/ext/java/jdi/client/debug/DebuggerPresenter.java
Fix problem with debugger tab, which opens after each refresh even if user hide it. Now it opens when connect to debugger or stop on breakpoint.
=> IIU-384: fix always opened debugger tab after refresh page

plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ext/DockerTerminalModule.java
There are two reasons here:
1. -n option is really unnecessary since we remove /home/user/che and recreate it here - https://github.com/codenvy/che/blob/master/assembly-ide-war/src/main/java/org/eclipse/che/api/deploy/ApiModule.java#L122 thus there cannot be a situation when a terminal folder exists in /home/user/che
2. Alpine and busybox do not recognize -n with cp. This it is impossible now to use alpine and busybox based images.
=> Remove unnecessary -n cp argument

plugin-java/che-plugin-java-ext-debugger-java-server/pom.xml, plugin-java/che-plugin-java-ext-debugger-java-server/src/main/java/org/eclipse/che/ide/ext/java/jdi/server/Debugger.java, plugin-java/che-plugin-java-ext-debugger-java-server/src/main/java/org/eclipse/che/ide/ext/java/jdi/server/DebuggerException.java
IDEX-4137: fix "Internal Server Error" error message in "Evaluate Expression" popup. Now it is displays actual message about  error, like "Unknown local variable or field someVar"
=> IDEX-4137: fix "Internal Server Error" error message in "Evaluate Expression" popup
