codenvy/che-plugins

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/runneractions/impl/environments/GetSystemEnvironmentsAction.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/util/GetEnvironmentsUtil.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/util/GetEnvironmentsUtilImpl.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/runneractions/impl/environments/GetSystemEnvironmentsActionTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/util/GetEnvironmentsUtilImplTest.java
=> IDEX-2263: Fixed bug related to opening project created from factory

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/runneractions/impl/StopAction.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/runneractions/impl/launch/subactions/StatusAction.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/runneractions/impl/launch/subactions/StatusActionTest.java
when stopping application - consider inprogress status as well, do not perform stop on stopped application
=> IDEX-2248: on stop app consider inprogress status, do not perform stop on stopped application

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/actions/ChooseRunnerAction.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/manager/RunnerManagerPresenter.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/impl/PropertiesEnvironmentPanel.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/actions/ChooseRunnerActionTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/manager/RunnerManagerPresenterTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/impl/PropertiesEnvironmentPanelTest.java
=> IDEX-2260: Fixed bugs with wrong ram of a custom environment

plugin-java/che-plugin-java-ext-ant/src/main/java/org/eclipse/che/ide/extension/ant/client/wizard/AntPagePresenter.java
IDEX-2266. Estimate project at update.
=> IDEX-2266. Estimate project at update.

plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/server/GitValueProviderFactory.java
IDEX-2158. Check whether the project git repository by performing git status.
=> IDEX-2158. Check whether the project git repository by performing git status

plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/client/SubversionClientService.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/client/SubversionClientServiceImpl.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/client/export/ExportPresenter.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/server/SubversionApi.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/server/rest/SubversionService.java, plugin-svn/che-plugin-svn-ext-subversion/src/test/java/org/eclipse/che/ide/ext/svn/client/export/ExportPresenterTest.java, plugin-svn/che-plugin-svn-ext-subversion/src/test/java/org/eclipse/che/ide/ext/svn/server/SubversionApiITest.java
=> IDEX-2072: Refactored export mechanism

plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/delete/DeleteRepositoryPresenter.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/init/InitRepositoryPresenter.java, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/delete/DeleteRepositoryPresenterTest.java, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/init/InitRepositoryPresenterTest.java
Refresh project tree after 'Delete repository' and 'Initialize Repository' actions.
=> IDEX-2253. Refresh project tree after 'Delete repository' and 'Initialize Repository' actions.

plugin-java/che-plugin-java-ext-debugger-java/src/main/java/org/eclipse/che/ide/ext/java/jdi/client/debug/DebuggerPresenter.java, plugin-java/che-plugin-java-ext-debugger-java/src/main/java/org/eclipse/che/ide/ext/java/jdi/client/debug/DebuggerVariable.java, plugin-java/che-plugin-java-ext-debugger-java/src/main/java/org/eclipse/che/ide/ext/java/jdi/client/debug/DebuggerView.java, plugin-java/che-plugin-java-ext-debugger-java/src/main/java/org/eclipse/che/ide/ext/java/jdi/client/debug/DebuggerViewImpl.java, plugin-java/che-plugin-java-ext-debugger-java/src/main/java/org/eclipse/che/ide/ext/java/jdi/client/debug/VariableNodeDataAdapter.java, plugin-java/che-plugin-java-ext-debugger-java/src/main/java/org/eclipse/che/ide/ext/java/jdi/client/debug/VariableTreeNodeRenderer.java, plugin-java/che-plugin-java-ext-debugger-java/src/test/java/org/eclipse/che/ide/ext/java/jdi/client/DebuggerTest.java, plugin-java/che-plugin-java-ext-debugger-java/src/test/java/org/eclipse/che/ide/ext/java/jdi/client/debug/DebuggerVariableTest.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/PropertiesPanelViewImpl.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/PropertiesPanelViewImpl.ui.xml, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/common/RAM.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/impl/PropertiesEnvironmentPanel.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/templates/defaultrunnerinfo/DefaultRunnerInfoImpl.java, plugin-runner/che-plugin-runner-ext-runner/src/main/resources/org/eclipse/che/ide/ext/runner/client/RunnerLocalizationConstant.properties, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/manager/info/MoreInfoImplTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/history/runner/RunnerWidgetTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/PropertiesPanelViewImplTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/templates/defaultrunnerinfo/DefaultRunnerInfoImplTest.java
=> IDEX-2300: Fixed bug related to selecting of variables in debug mode. Fixed some notes.

plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/client/action/ChangeCredentialsAction.java
=> IDEX-2358 checking for attribute svn.repository.url on root project and not on submodule

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/RunnerResources.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/manager/RunnerManagerPresenter.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/PropertiesPanelViewImpl.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/PropertiesPanelViewImpl.ui.xml, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/impl/PropertiesEnvironmentPanel.java, plugin-runner/che-plugin-runner-ext-runner/src/main/resources/org/eclipse/che/ide/ext/runner/client/runner.css, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/PropertiesPanelViewImplTest.java
=> IDEX-2245: Fixed incorrect behavior of properties panel in sdk

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/RunnerLocalizationConstant.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/manager/RunnerManagerPresenter.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/manager/RunnerManagerView.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/manager/RunnerManagerViewImpl.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/manager/RunnerManagerViewImpl.ui.xml, plugin-runner/che-plugin-runner-ext-runner/src/main/resources/org/eclipse/che/ide/ext/runner/client/RunnerLocalizationConstant.properties, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/manager/RunnerManagerPresenterTest.java
IDEX-2334. Display debug port in the UI.
=> IDEX-2334. Display debug port in the UI.

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/RunnerLocalizationConstant.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/history/HistoryPresenter.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/terminal/container/TerminalContainerPresenter.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/terminal/panel/TerminalImpl.java, plugin-runner/che-plugin-runner-ext-runner/src/main/resources/org/eclipse/che/ide/ext/runner/client/RunnerLocalizationConstant.properties, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/history/HistoryPresenterTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/terminal/container/TerminalContainerPresenterTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/terminal/panel/TerminalImplTest.java
=> IDEX-2374: Fixed resource unavailable screen in terminal

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/impl/PropertiesEnvironmentPanel.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/templates/TemplatesPresenter.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/templates/TemplatesPresenterTest.java
=> IDEX-2396: Fix losing focus after renaming

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/impl/PropertiesEnvironmentPanel.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/templates/environment/EnvironmentWidget.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/impl/PropertiesEnvironmentPanelTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/templates/environment/EnvironmentWidgetTest.java
=> IDEX-2401: Fixed bug related to renaming of default runner

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/PropertiesPanelViewImpl.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/impl/PropertiesEnvironmentPanel.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/impl/PropertiesEnvironmentPanelTest.java
=> IDEX-2404 Copy scope environment from System scope has wrong type

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/actions/CreateCustomRunnerAction.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/PropertiesPanelView.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/PropertiesPanelViewImpl.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/impl/PropertiesEnvironmentPanel.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/templates/TemplatesContainer.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/templates/TemplatesPresenter.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/util/NameGenerator.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/actions/CreateCustomRunnerActionTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/PropertiesPanelViewImplTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/impl/PropertiesEnvironmentPanelTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/util/NameGeneratorTest.java
=> IDEX-2402: Fixed bug related to incorrect environment name. Added environment name validation.

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/manager/info/MoreInfoImpl.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/runneractions/impl/CheckRamAndRunAction.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/history/runner/RunnerWidget.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/PropertiesPanelViewImpl.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/common/RAM.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/templates/defaultrunnerinfo/DefaultRunnerInfoImpl.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/util/RunnerUtilImpl.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/actions/RunActionTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/manager/RunnerManagerPresenterTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/manager/info/MoreInfoImplTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/models/RunnerImplTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/runneractions/impl/RunActionTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/history/runner/RunnerWidgetTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/PropertiesPanelPresenterTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/PropertiesPanelViewImplTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/common/RAMTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/impl/PropertiesEnvironmentPanelTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/impl/PropertiesRunnerPanelTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/templates/defaultrunnerinfo/DefaultRunnerInfoImplTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/util/RunnerUtilImplTest.java
Reverts codenvy/che-plugins#73
=> Revert "Change memory values from 128, 512 ... to 100, 500."

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/RunnerExtension.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/runneractions/impl/GetRunningProcessesAction.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/templates/TemplatesViewImpl.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/templates/TemplatesViewImpl.ui.xml
=> IDEX-2399: don't show 'Create new' button from sdk

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/console/panel/MessageBuilder.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/console/panel/MessageType.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/console/panel/MessageBuilderTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/console/panel/MessageTypeTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/resources/org/eclipse/che/ide/ext/runner/client/tabs/console/panel/MessageWithContent.txt
=> IDEX-2390: Fixed bug related to stopping application after page reload in sdk mode

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/impl/PropertiesEnvironmentPanel.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/impl/PropertiesRunnerPanel.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/impl/PropertiesRunnerPanelTest.java
IDEX-2334. Move Port Mapping from PropertiesEnvironmentPanel in PropertiesRunnerPanel.
=> IDEX-2334. Move Port Mapping from PropertiesEnvironmentPanel in PropertiesRunnerPanel.

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/manager/RunnerManagerPresenter.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/runneractions/impl/RunAction.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/util/EnvironmentIdValidator.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/manager/RunnerManagerPresenterTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/runneractions/impl/RunActionTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/util/EnvironmentIdValidatorTest.java
=> IDEX-2423: validate the address of environment

plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/branch/BranchPresenter.java, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/branch/BranchPresenterTest.java
Disable 'Rename' button for remote branches.
Disable 'Checkout' and 'Delete' buttons for current branch.
Update tests.
=> IDEX-1208. Disable 'Rename' button for remote branches. Disable 'Checkout' and 'Delete' buttons for current branch. Update tests.

plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/server/SubversionApi.java
=> IDEX-2504 - --no-ignore option should be set when isShowIgnored() is true and not the contrary

plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/GitLocalizationConstant.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/branch/BranchPresenter.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/server/GitConnection.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/server/nativegit/NativeGit.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/server/nativegit/NativeGitConnection.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/server/nativegit/commands/BranchRenameCommand.java, plugin-git/che-plugin-git-ext-git/src/main/resources/org/eclipse/che/ide/ext/git/client/GitLocalizationConstant.properties, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/branch/BranchPresenterTest.java
IDEX-900. Rename remote branch.
=> IDEX-900. Rename remote branch.

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/manager/RunnerManagerPresenter.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/manager/RunnerManagerPresenterTest.java
=> IDEX-2450: Fixed bug related to wrong information about scope

plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/client/commit/CommitPresenter.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/client/commit/CommitView.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/client/commit/CommitViewImpl.java, plugin-svn/che-plugin-svn-ext-subversion/src/test/java/org/eclipse/che/ide/ext/svn/client/commit/CommitPresenterTest.java
@stour @skabashnyuk @vparfonov
=> IDEX-2494: Update list of changed files when commit "mode" (commit all/commit selection) changes

plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/client/SubversionClientService.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/client/SubversionClientServiceImpl.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/client/property/PropertyEditorPresenter.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/client/property/PropertyEditorView.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/client/property/PropertyEditorViewImpl.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/client/property/PropertyEditorViewImpl.ui.xml, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/server/SubversionApi.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/server/rest/SubversionService.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/shared/PropertyGetRequest.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/shared/PropertyListRequest.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/resources/org/eclipse/che/ide/ext/svn/client/SubversionExtensionLocalizationConstants.properties
=> IDEX-2412 - displaying property current value in Property window

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/actions/ChooseRunnerAction.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/models/RunnerImpl.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/runneractions/impl/environments/GetProjectEnvironmentsAction.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/impl/PropertiesEnvironmentPanel.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/util/EnvironmentIdValidator.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/actions/ChooseRunnerActionTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/manager/RunnerManagerPresenterTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/util/EnvironmentIdValidatorTest.java
=> IDEX-2521: fixed path of the project environments

plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/client/projecttree/ModuleNode.java
=> IDEX-2214: Fixed wrong behaviour during maven module renaming

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/RunnerLocalizationConstant.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/manager/RunnerManagerPresenter.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/runneractions/impl/RunAction.java, plugin-runner/che-plugin-runner-ext-runner/src/main/resources/org/eclipse/che/ide/ext/runner/client/RunnerLocalizationConstant.properties, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/manager/RunnerManagerPresenterTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/runneractions/impl/RunActionTest.java
=> IDEX-2495: Corrected runner status if it's in the queue

plugin-sdk/che-plugin-sdk-env-local/src/main/java/org/eclipse/che/env/local/client/LocalEnvironmentExtension.java, plugin-sdk/che-plugin-sdk-env-local/src/main/java/org/eclipse/che/env/local/client/lacation/WorkspaceLocationPresenter.java, plugin-sdk/che-plugin-sdk-env-local/src/main/java/org/eclipse/che/env/local/client/lacation/WorkspaceLocationViewImpl.java
=> IDEX-2457: show initialization window with workspace location

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/terminal/container/TerminalContainerPresenter.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/terminal/panel/TerminalImpl.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/terminal/container/TerminalContainerPresenterTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/terminal/panel/TerminalImplTest.java
=> IDEX-2531: Fixed terminal behavior after restarting runner

plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/server/nativegit/CredentialsLoader.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/server/nativegit/NativeGitConnection.java
=> IDEX-2460: Fixed perform Git push operation after using github - https link on sdk

plugin-ssh/che-plugin-ssh-ext-sshkey/src/main/java/org/eclipse/che/ide/ext/ssh/client/SshLocalizationConstant.java, plugin-ssh/che-plugin-ssh-ext-sshkey/src/main/java/org/eclipse/che/ide/ext/ssh/client/manage/SshKeyManagerPresenter.java, plugin-ssh/che-plugin-ssh-ext-sshkey/src/main/resources/org/eclipse/che/ide/ext/ssh/client/SshLocalizationConstant.properties, plugin-ssh/che-plugin-ssh-ext-sshkey/src/test/java/org/eclipse/che/ide/ext/ssh/client/manage/SshKeyManagerPresenterTest.java
IDEX-2567. Use codenvy window then try generate ssh key instead of browser pop up.
=> IDEX-2567. Use codenvy window then try generate ssh key instead of browser pop up.

plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/client/SubversionClientServiceImpl.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/client/action/ResolveAction.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/client/resolve/ResolvePresenter.java
=> IDEX-2227: Enable Resolve action in menu only if project contains conflicts

plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/server/SubversionApi.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/server/SubversionProjectImporter.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/server/upstream/UpstreamUtils.java
=> IDEX-2225: Add more info in notification during svn checkout

plugin-sdk/che-plugin-sdk-env-local/src/main/java/org/eclipse/che/env/local/client/lacation/WorkspaceLocationViewImpl.java
=> Add ability to handle Enter key when user specify workspace location.

plugin-java/che-plugin-java-ext-java-codeassistant/src/main/java/org/eclipse/che/jdt/dom/ASTNodes.java, plugin-java/che-plugin-java-ext-java-codeassistant/src/main/java/org/eclipse/che/jdt/internal/core/JavaModelManager.java, plugin-java/che-plugin-java-ext-java-codeassistant/src/main/java/org/eclipse/che/jdt/internal/core/JavaProject.java, plugin-java/che-plugin-java-ext-java-codeassistant/src/main/java/org/eclipse/che/jdt/internal/core/Openable.java, plugin-java/che-plugin-java-ext-java-codeassistant/src/main/java/org/eclipse/che/jdt/internal/core/PackageFragmentRoot.java, plugin-java/che-plugin-java-ext-java-codeassistant/src/main/java/org/eclipse/che/jdt/internal/core/search/Util.java, plugin-java/che-plugin-java-ext-java-codeassistant/src/main/java/org/eclipse/che/jdt/javadoc/ASTProvider.java, plugin-java/che-plugin-java-ext-java-codeassistant/src/main/java/org/eclipse/che/jdt/javadoc/JavaElementLabels.java, plugin-java/che-plugin-java-ext-java-codeassistant/src/main/java/org/eclipse/che/jdt/javadoc/JavaElementLinks.java, plugin-java/che-plugin-java-ext-java-codeassistant/src/main/java/org/eclipse/che/jdt/util/JavaModelUtil.java
IDEX-2462. Fixed license for some classes.
=> IDEX-2462. Fixed license for some classes.

plugin-java/che-plugin-java-ext-java/src/main/java/org/eclipse/che/ide/ext/java/client/action/NewPackageAction.java
Added able return the corrected value for replacement in InputValidator.
=> IDEX-2526. Added able return the corrected value for replacement in InputValidator

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/PropertiesPanelViewImpl.ui.xml
Lined up Project Default switch with it's label
=> IDEX-2566 corrected position of ProjectDefault switch

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/RunnerLocalizationConstant.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/history/HistoryPresenter.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/history/HistoryView.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/history/HistoryViewImpl.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/history/HistoryViewImpl.ui.xml, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/history/runner/RunnerWidget.java, plugin-runner/che-plugin-runner-ext-runner/src/main/resources/org/eclipse/che/ide/ext/runner/client/RunnerLocalizationConstant.properties, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/history/HistoryPresenterTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/history/HistoryViewImplTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/history/runner/RunnerWidgetTest.java
=> IDEX-2529: added 'clear all inactive runners' button

plugin-java/che-plugin-java-ext-ant/src/main/java/org/eclipse/che/ide/extension/ant/client/projecttree/AntProjectNode.java, plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/client/actions/CreateMavenModuleAction.java, plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/client/projecttree/MavenProjectNode.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/client/common/filteredtree/FilteredProjectNode.java
=> IDEX-2607: Set the context to the current module (not only top level project)

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/manager/RunnerManagerViewImpl.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/manager/RunnerManagerViewImpl.ui.xml, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/manager/button/ButtonWidgetImpl.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/manager/button/ButtonWidgetImpl.ui.xml, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/common/item/ItemWidgetImpl.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/common/item/ItemWidgetImpl.ui.xml, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/console/button/ConsoleButtonImpl.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/history/HistoryViewImpl.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/history/HistoryViewImpl.ui.xml, plugin-runner/che-plugin-runner-ext-runner/src/main/resources/org/eclipse/che/ide/ext/runner/client/runner.css, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/manager/RunnerManagerViewImplTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/common/item/ItemWidgetImplTest.java
=> IDEX-2546: fixed problem with displaying buttons on the runner panel

plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/branch/BranchPresenter.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/reset/commit/ResetToCommitPresenter.java, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/branch/BranchPresenterTest.java, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/reset/commit/ResetToCommitPresenterTest.java
Use OpenProjectEvent when we can have unconfigured state of the project.
=> IDEX-2642, IDEX-2629. Use OpenProjectEvent when we can have unconfigured state of the project.

plugin-grunt/che-plugin-grunt-runner/src/main/java/org/eclipse/che/plugin/grunt/runner/GruntRunner.java, plugin-gulp/che-plugin-gulp-runner/src/main/java/org/eclipse/che/plugin/gulp/runner/GulpRunner.java, plugin-sdk/che-plugin-sdk-runner/src/main/resources/codenvyPlatform/src/main/webapp/WEB-INF/classes/codenvy/codenvy-api-configuration.properties
=> IDEX-1038: removed unusable properties

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/templates/TemplatesPresenter.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/templates/TemplatesView.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/templates/TemplatesViewImpl.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/templates/TemplatesViewImpl.ui.xml, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/templates/TemplatesPresenterTest.java
=> IDEX-2565: fixed bug with scrolling elements of the list of environments

plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/GitServiceClient.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/GitServiceClientImpl.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/server/nativegit/NativeGitConnection.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/server/nativegit/commands/BranchCheckoutCommand.java
IDEX-2440. Added the ability to create a new branch using a 'BranchCheckoutCommand'.
=> IDEX-2440. Added the ability to create a new branch using a 'BranchCheckoutCommand'.

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/runneractions/impl/CheckRamAndRunAction.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/runneractions/impl/CheckRamAndRunActionTest.java
=> IDEX-2492: show Configs after pushing Configure RAM button

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/runneractions/impl/launch/subactions/StatusAction.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/templates/TemplatesPresenter.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/runneractions/impl/launch/subactions/StatusActionTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/templates/TemplatesPresenterTest.java
=> IDEX-2497: fixed problem with re-running project from dashboard

plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/action/FetchAction.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/action/GitAction.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/action/InitRepositoryAction.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/action/PullAction.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/action/PushAction.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/action/RemoveFromIndexAction.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/action/ShowRemoteAction.java, plugin-java/che-plugin-java-ext-client/src/main/java/org/eclipse/che/ide/ext/java/client/action/NewPackageAction.java, plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/client/actions/UpdateDependencyAction.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/actions/MachinePerspectiveAction.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/inject/MachineGinModule.java, plugin-machine/che-plugin-machine-ext-client/src/test/java/org/eclipse/che/ide/extension/machine/client/actions/MachinePerspectiveActionTest.java
@azatsarynnyy @vparfonov @evidolob
=> IDEX-2636: Added ability define behaviour for main menu and toolbar depending on Perspective

plugin-java/che-plugin-java-runner-webapps/src/main/java/org/eclipse/che/runner/webapps/WindowsTomcatServer.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/console/panel/MessageBuilder.java, plugin-runner/che-plugin-runner-ext-runner/src/test/resources/org/eclipse/che/ide/ext/runner/client/tabs/console/panel/MessageWithContent.txt, plugin-runner/che-plugin-runner-ext-runner/src/test/resources/org/eclipse/che/ide/ext/runner/client/tabs/console/panel/MessageWithoutTypeWithContent.txt
=> IDEX-2663: fixed problem with re-running application on Win OS

plugin-codemirror/che-plugin-codemirror-editorwidget/src/main/java/org/eclipse/che/ide/editor/codemirror/client/CodeMirrorDocument.java
Hello,
I need this improvement for real time live editing plugin
This goes with https://github.com/codenvy/che-core/pull/122
Thanks,
=> Demo flux: adding removed char count to document change event

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/impl/PropertiesEnvironmentPanel.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/tabs/templates/environment/EnvironmentWidget.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/properties/panel/impl/PropertiesEnvironmentPanelTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/tabs/templates/environment/EnvironmentWidgetTest.java
=> IDEX-2663: fixed problem with default runner switch

plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/actions/RunAction.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/inject/factories/ModelsFactory.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/manager/RunnerManager.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/manager/RunnerManagerPresenter.java, plugin-runner/che-plugin-runner-ext-runner/src/main/java/org/eclipse/che/ide/ext/runner/client/models/RunnerImpl.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/actions/RunActionTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/manager/RunnerManagerPresenterTest.java, plugin-runner/che-plugin-runner-ext-runner/src/test/java/org/eclipse/che/ide/ext/runner/client/models/RunnerImplTest.java
=> IDEX-2701: show correct value of environment scope into properties panel

plugin-codemirror/che-plugin-codemirror-jso/src/main/java/org/eclipse/che/ide/editor/codemirrorjso/client/CMKeymapOverlay.java
=> IDEX-2711 - adding removeBinding method to clean an existing Codemirror keybinding

plugin-svn/che-plugin-svn-ext-subversion/src/test/java/org/eclipse/che/ide/ext/svn/server/SubversionApiITest.java, plugin-svn/che-plugin-svn-ext-subversion/src/test/java/org/eclipse/che/ide/ext/svn/server/SubversionProjectImporterTest.java
Fixed svn test for passing on Windows OS
=> IDEX-2665: Fixed svn test for passing on Windows OS

plugin-java/che-plugin-java-ext-debugger-java/src/main/java/org/eclipse/che/ide/ext/java/jdi/client/debug/remotedebug/RemoteDebugViewImpl.java, plugin-java/che-plugin-java-ext-debugger-java/src/main/java/org/eclipse/che/ide/ext/java/jdi/server/Debugger.java, plugin-java/che-plugin-java-ext-debugger-java/src/test/java/org/eclipse/che/ide/ext/java/jdi/client/debug/remotedebug/RemoteDebugViewImplTest.java
=> IDEX-2558: added a validation for parameters of remote debug

plugin-svn/che-plugin-svn-ext-subversion/src/test/java/org/eclipse/che/ide/ext/svn/server/SubversionApiITest.java, plugin-svn/che-plugin-svn-ext-subversion/src/test/java/org/eclipse/che/ide/ext/svn/server/SubversionProjectImporterTest.java
Fixed svn tests for passing on Windows OS
=> IDEX-2665: Fixed svn tests for passing on Windows OS

plugin-sdk/che-plugin-sdk-env-local/src/main/java/org/eclipse/che/env/local/client/CheConnectionClosedInformer.java, plugin-sdk/che-plugin-sdk-env-local/src/main/java/org/eclipse/che/env/local/client/LocalizationConstant.java, plugin-sdk/che-plugin-sdk-env-local/src/main/java/org/eclipse/che/env/local/client/inject/LocalEnvironmentGinModule.java, plugin-sdk/che-plugin-sdk-env-local/src/main/resources/org/eclipse/che/env/local/client/LocalizationConstant.properties
Added ability to handle each status code when a connection was closed. 
Show message dialog for Che assembly when a connection was closed.
=> IDEX-2350. Added ability to handle each status code when a connection was closed. Show message dialog for Che assembly when a connection was closed.

plugin-java/che-plugin-java-ext-java-codeassistant/pom.xml
Exclude quinox transitive dependency to prevent class loading errors
=> Exclude 'equinox' transitive dependency

plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/GitLocalizationConstant.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/importer/page/GitImporterPagePresenter.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/importer/page/GitImporterPageView.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/importer/page/GitImporterPageViewImpl.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/importer/page/GitImporterPageViewImpl.ui.xml, plugin-git/che-plugin-git-ext-git/src/main/resources/org/eclipse/che/ide/ext/git/client/GitLocalizationConstant.properties, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/importer/page/GitImporterPagePresenterTest.java, plugin-github/che-plugin-github-ext-github/src/main/java/org/eclipse/che/ide/ext/github/client/GitHubLocalizationConstant.java, plugin-github/che-plugin-github-ext-github/src/main/java/org/eclipse/che/ide/ext/github/client/importer/page/GithubImporterPagePresenter.java, plugin-github/che-plugin-github-ext-github/src/main/java/org/eclipse/che/ide/ext/github/client/importer/page/GithubImporterPageView.java, plugin-github/che-plugin-github-ext-github/src/main/java/org/eclipse/che/ide/ext/github/client/importer/page/GithubImporterPageViewImpl.java, plugin-github/che-plugin-github-ext-github/src/main/java/org/eclipse/che/ide/ext/github/client/importer/page/GithubImporterPageViewImpl.ui.xml, plugin-github/che-plugin-github-ext-github/src/main/resources/org/eclipse/che/ide/ext/github/client/GitHubLocalizationConstant.properties
@vparfonov @skabashnyuk @gazarenkov
=>  IDEX-1556 Add optionally Property page to Import Wizard

plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/machine/appliance/MachineAppliancePresenter.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/machine/appliance/MachineApplianceView.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/machine/appliance/MachineApplianceViewImpl.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/machine/appliance/MachineApplianceViewImpl.ui.xml, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/machine/panel/MachinePanelPresenter.java, plugin-machine/che-plugin-machine-ext-client/src/test/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/machine/appliance/MachineAppliancePresenterTest.java, plugin-machine/che-plugin-machine-ext-client/src/test/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/machine/appliance/MachineApplianceViewImplTest.java, plugin-machine/che-plugin-machine-ext-client/src/test/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/machine/panel/MachinePanelPresenterTest.java
=> IDEX-2894: Fixed losing terminal history if switch to recipes tab

plugin-sdk/che-plugin-sdk-runner/src/main/resources/tomcat/bin/setenv.bat, plugin-sdk/che-plugin-sdk-runner/src/main/resources/tomcat/bin/setenv.sh
Merge only after codenvy/codenvy-dev-resources IDEX-2800 branch is merged
=> IDEX-2800 Changed CODENVY_LOCAL_CONF_DIR to CHE_LOCAL_CONF_DIR

plugin-sdk/che-plugin-sdk-runner/src/main/resources/tomcat/bin/setenv.sh
Do not merge until codenvy/codenvy-dev-resources IDEX-2801 branch is merged
=> IDEX-2801 Changed CODENVY_LOGS_DIR to CHE_LOGS_DIR

plugin-docker/che-plugin-docker-client/pom.xml, plugin-docker/che-plugin-docker-client/src/main/java/org/eclipse/che/plugin/docker/client/DockerConnector.java, plugin-docker/che-plugin-docker-client/src/main/java/org/eclipse/che/plugin/docker/client/DockerConnectorConfiguration.java, plugin-docker/che-plugin-docker-client/src/test/java/org/eclipse/che/plugin/docker/client/DockerConnectorConfigurationTest.java, plugin-docker/che-plugin-docker-client/src/test/java/org/eclipse/che/plugin/docker/client/DockerfileParserTest.java, plugin-docker/che-plugin-docker-client/src/test/java/org/eclipse/che/plugin/docker/client/ProgressStatusReaderTest.java, plugin-docker/che-plugin-docker-client/src/test/java/org/eclipse/che/plugin/docker/client/SystemInfoDriverStatusTest.java
Variables define the boot2docker configuration (like ip address, protocol, certificates folder, etc)
=> IDEX-2905 Allow to use Docker Machine system variables (master branch)

plugin-sdk/che-plugin-sdk-tools/src/main/java/org/eclipse/che/ide/sdk/tools/InstallExtension.java
(in addition to client only and client+server extensions)
=> IDEX-2964 Allow to use server-side only extension 

plugin-docker/che-plugin-docker-ext-client/pom.xml, plugin-docker/che-plugin-docker-ext-client/src/main/java/org/eclipse/che/plugin/docker/ext/client/manage/input/InputDialog.java, plugin-docker/che-plugin-docker-ext-client/src/main/java/org/eclipse/che/plugin/docker/ext/client/manage/input/callback/InputCallback.java, plugin-docker/pom.xml
seems like this module is not enabled and can't compile without these changes
=> Missing maven module

plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/machine/MachineStatusNotifier.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/machine/panel/MachinePanelPresenter.java, plugin-machine/che-plugin-machine-ext-client/src/test/java/org/eclipse/che/ide/extension/machine/client/machine/MachineStateNotifierTest.java, plugin-machine/che-plugin-machine-ext-client/src/test/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/machine/panel/MachinePanelPresenterTest.java
Changed machine status channel. 
Fixed refresh list of machines and menu 'Machine' after destroy last machine.
=> IDEX-2992. Changed machine status channel. Fixed refresh list of machines and menu 'Machine' after destroy last machine.

plugin-ssh/che-plugin-ssh-git-native/src/main/java/org/eclipse/che/git/impl/nativegit/ssh/SshKeyProviderImpl.java
@skabashnyuk Can you review these changes?
=> IDEX-2234 Removed autogenerating of ssh keys

plugin-bower/che-plugin-bower-ext-client/src/main/java/org/eclipse/che/plugin/bower/client/menu/BowerInstallAction.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/branch/BranchPresenter.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/checkout/CheckoutReferencePresenter.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/delete/DeleteRepositoryPresenter.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/init/InitRepositoryPresenter.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/merge/MergePresenter.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/pull/PullPresenter.java, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/branch/BranchPresenterTest.java, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/delete/DeleteRepositoryPresenterTest.java, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/init/InitRepositoryPresenterTest.java, plugin-github/che-plugin-github-ext-github/src/main/java/org/eclipse/che/ide/ext/github/client/importer/page/GithubImporterPagePresenter.java, plugin-java/che-plugin-java-ext-java/src/main/java/org/eclipse/che/ide/ext/java/client/action/NewPackageAction.java, plugin-java/che-plugin-java-ext-java/src/main/java/org/eclipse/che/ide/ext/java/client/newsourcefile/NewJavaSourceFilePresenter.java, plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/client/MavenExtension.java, plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/client/module/CreateMavenModulePresenter.java, plugin-npm/che-plugin-npm-ext-client/src/main/java/org/eclipse/che/plugin/npm/client/menu/NpmInstallAction.java, plugin-yeoman/che-plugin-yeoman-ext-client/src/main/java/org/eclipse/che/plugin/yeoman/client/panel/YeomanPartPresenter.java, plugin-yeoman/che-plugin-yeoman-ext-client/src/test/java/org/eclipse/che/plugin/yeoman/client/panel/YeomanPartPresenterTest.java
=> IDEX-2971: Tree collapse fixes

plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/remote/RemotePresenter.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/remote/RemoteView.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/remote/RemoteViewImpl.java
@vparfonov Can you review these changes?
=> IDEX-1972 Added checking actuality of remote selection

plugin-docker/che-plugin-docker-runner/src/main/java/org/eclipse/che/plugin/docker/runner/EmbeddedDockerRunnerRegistryPlugin.java
the format is /my/runner and not /my\runner
=> IDEX-3046 On Windows, env should also be in url format

plugin-github/che-plugin-github-ext-github/src/main/java/org/eclipse/che/ide/ext/github/client/GitHubClientService.java, plugin-github/che-plugin-github-ext-github/src/main/java/org/eclipse/che/ide/ext/github/client/GitHubClientServiceImpl.java, plugin-github/che-plugin-github-ext-github/src/main/java/org/eclipse/che/ide/ext/github/server/GitHubFactory.java, plugin-github/che-plugin-github-ext-github/src/main/java/org/eclipse/che/ide/ext/github/server/rest/GitHubService.java
=> Code clean up

plugin-java/che-plugin-java-ext-lang-client/pom.xml, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/JavaLocalizationConstant.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/editor/JavaReconcilerStrategy.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/RefactoringUpdater.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/move/wizard/MovePresenter.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/move/wizard/MoveView.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/move/wizard/MoveViewImpl.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/move/wizard/MoveViewImpl.ui.xml, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/move/wizard/ProjectsAndPackagesModel.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/preview/PreviewChangesModel.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/preview/PreviewPresenter.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/preview/PreviewView.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/preview/PreviewViewImpl.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/preview/PreviewViewImpl.ui.xml, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/service/RefactoringServiceClient.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/service/RefactoringServiceClientImpl.java, plugin-java/che-plugin-java-ext-lang-client/src/main/resources/org/eclipse/che/ide/ext/java/client/JavaLocalizationConstant.properties, plugin-java/che-plugin-java-ext-lang-client/src/test/java/org/eclipse/che/ide/ext/java/client/refactoring/move/wizard/MovePresenterTest.java, plugin-java/che-plugin-java-ext-lang-client/src/test/java/org/eclipse/che/ide/ext/java/client/refactoring/preview/PreviewPresenterTest.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/machine/appliance/recipe/RecipeViewImpl.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/machine/appliance/recipe/RecipeViewImpl.ui.xml, plugin-orion/che-plugin-orion-compare/pom.xml, plugin-orion/che-plugin-orion-compare/src/main/java/org/eclipse/che/ide/orion/compare/CompareFactoryImpl.java, plugin-orion/che-plugin-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/OrionEditorExtension.java, plugin-orion/che-plugin-orion-editor/src/main/resources/org/eclipse/che/ide/editor/orion/client/style/orion_codenvy_theme.css
=> IDEX-3017: improved move refactoring wizard

plugin-java/che-plugin-java-ext-java/src/main/java/org/eclipse/che/ide/ext/java/client/editor/FileWatcher.java
Fixed applying changes from base class to extended class
=> IDEX-3000: Fixed applying changes from base class to extended class

plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/merge/MergePresenter.java, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/merge/MergePresenterTest.java
Please, review fix and merge changes into the master.
=> IDEX-1955: fixed error when the remote branches did not disappear after remove the remote repository

plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/machine/MachineManager.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/machine/MachineStatusNotifier.java
=> IDEX-3109: Improved behaviour of workspace open window

plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/settings/property/PropertyWidgetImpl.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/settings/property/PropertyWidgetImpl.ui.xml, plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/client/wizard/MavenPageViewImpl.java, plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/client/wizard/MavenPageViewImpl.ui.xml, plugin-machine/che-plugin-machine-ext-client/src/main/resources/org/eclipse/che/ide/extension/machine/client/machine.css
=> IDEX-3071: Replace ListBox widget

plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/DockerInstanceProvider.java, plugin-docker/che-plugin-docker-machine/src/test/java/org/eclipse/che/plugin/docker/machine/DockerInstanceProviderTest.java
Setup in developer machine, environment varable with ID of a workspace for which this machine has been created.
Fix few copy-past error in tests
=> IDEX-3188:

plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/DockerInstanceProvider.java, plugin-docker/che-plugin-docker-machine/src/test/java/org/eclipse/che/plugin/docker/machine/DockerInstanceProviderTest.java, plugin-docker/che-plugin-docker-machine/src/test/java/org/eclipse/che/plugin/docker/machine/integration/ServiceTest.java
This set of lines will be add to /etc/hosts on running docker container
=> CLDIDE-2537 Add ability to configure extra hosts for docker images.

plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/DockerInstanceProvider.java, plugin-docker/che-plugin-docker-machine/src/test/java/org/eclipse/che/plugin/docker/machine/DockerInstanceProviderTest.java
Changed injected variable from array to string with ',' delimiter to allow inject NULL from configuration
Signed-off-by: Sergii Kabashniuk <skabashnyuk@codenvy.com>
=> CLDIDE-2537 Changed injected variable from array to string

plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/server/inject/MavenModule.java, plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/server/projecttype/handler/RemoveMavenModuleHandler.java, plugin-java/che-plugin-java-ext-maven/src/test/java/org/eclipse/che/ide/extension/maven/server/projecttype/handler/RemoveMavenModuleHandlerTest.java, plugin-java/che-plugin-java-maven-tools/src/main/java/org/eclipse/che/ide/maven/tools/Model.java, plugin-java/che-plugin-java-maven-tools/src/test/java/org/eclipse/che/ide/maven/tools/ModelTest.java
Add RemoveModuleHandler for delete module from pom.xml. 
Add module in '.codenvy/modules' at importing project.
=> IDEX-2899. Add RemoveModuleHandler for delete module from pom.xml. Add module in '.codenvy/modules' at importing project.

plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/machine/appliance/MachineApplianceViewImpl.java
=> IDEX-3147. Fix resize of the terminal

plugin-sdk/che-plugin-sdk-runner/src/main/resources/codenvyPlatform/pom.xml
Change Che pom.xml parent values
=> IDEX-2982. Change Che pom.xml parent values

plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/GitOutputPartPresenter.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/checkout/CheckoutReferencePresenter.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/history/HistoryPresenter.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/reset/commit/ResetToCommitPresenter.java, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/checkout/CheckoutReferenceTest.java, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/reset/commit/ResetToCommitPresenterTest.java, plugin-java/che-plugin-java-ext-debugger-java-client/src/main/java/org/eclipse/che/ide/ext/java/jdi/client/debug/DebuggerPresenter.java, plugin-java/che-plugin-java-ext-debugger-java-client/src/test/java/org/eclipse/che/ide/ext/java/jdi/client/DebuggerTest.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/dependenciesupdater/DependenciesUpdater.java, plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/client/MavenExtension.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/MachineExtension.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/actions/ExecuteSelectedCommandAction.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/actions/SelectCommandComboBoxReady.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/command/edit/EditCommandsPresenter.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/command/valueproviders/CurrentProjectPathProvider.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/outputspanel/OutputsContainerPresenter.java, plugin-machine/che-plugin-machine-ext-client/src/test/java/org/eclipse/che/ide/extension/machine/client/actions/ExecuteSelectedCommandActionTest.java, plugin-machine/che-plugin-machine-ext-client/src/test/java/org/eclipse/che/ide/extension/machine/client/command/valueproviders/CurrentProjectPathProviderTest.java, plugin-sdk/che-plugin-sdk-env-local/src/main/java/org/eclipse/che/env/local/client/location/WorkspaceLocationViewImpl.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/client/SubversionExtension.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/client/action/ResolveReady.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/client/common/SubversionActionPresenter.java
=> IDEX-2873: Add ability to show several opened projects in project tree

plugin-java/che-plugin-java-ext-maven/pom.xml, plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/client/MavenLocalizationConstant.java, plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/client/wizard/MavenPagePresenter.java, plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/client/wizard/MavenPageViewImpl.java, plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/client/wizard/MavenPageViewImpl.ui.xml, plugin-java/che-plugin-java-ext-maven/src/main/resources/org/eclipse/che/ide/extension/maven/Maven.gwt.xml, plugin-java/che-plugin-java-ext-maven/src/main/resources/org/eclipse/che/ide/extension/maven/client/MavenLocalizationConstant.properties
Add tooltips on maven page. 
Fix NPE.
=> IDEX-3138. Add tooltips on maven page. Fix NPE.

plugin-java/che-plugin-java-ext-jdt/che-jdt-ext-machine/src/main/java/org/eclipse/che/jdt/refactoring/DtoConverter.java, plugin-java/che-plugin-java-ext-jdt/che-jdt-ext-machine/src/main/java/org/eclipse/che/jdt/refactoring/RefactoringManager.java, plugin-java/che-plugin-java-ext-jdt/che-jdt-ext-machine/src/main/java/org/eclipse/che/jdt/refactoring/session/RefactoringSession.java, plugin-java/che-plugin-java-ext-jdt/che-jdt-ext-machine/src/main/java/org/eclipse/che/jdt/refactoring/session/RenameLinkedModeRefactoringSession.java, plugin-java/che-plugin-java-ext-jdt/che-jdt-ext-machine/src/main/java/org/eclipse/che/jdt/rest/RefactoringService.java, plugin-java/che-plugin-java-ext-jdt/che-jdt-ext-machine/src/main/java/org/eclipse/jdt/internal/corext/refactoring/AbstractJavaElementRenameChange.java, plugin-java/che-plugin-java-ext-jdt/che-jdt-ext-machine/src/main/java/org/eclipse/jdt/internal/corext/refactoring/changes/CompilationUnitReorgChange.java, plugin-java/che-plugin-java-ext-jdt/che-jdt-ext-machine/src/main/java/org/eclipse/jdt/internal/corext/refactoring/changes/RenamePackageChange.java, plugin-java/che-plugin-java-ext-jdt/che-jdt-ext-machine/src/main/java/org/eclipse/jdt/internal/ui/refactoring/RefactoringExecutionHelper.java, plugin-java/che-plugin-java-ext-jdt/che-jdt-ext-machine/src/main/java/org/eclipse/jdt/ui/refactoring/RenameSupport.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/move/wizard/MovePresenter.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/preview/PreviewPresenter.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/JavaRefactoringRename.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/RenamePresenter.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/service/RefactoringServiceClient.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/service/RefactoringServiceClientImpl.java, plugin-java/che-plugin-java-ext-lang-client/src/test/java/org/eclipse/che/ide/ext/java/client/refactoring/move/wizard/MovePresenterTest.java, plugin-java/che-plugin-java-ext-lang-client/src/test/java/org/eclipse/che/ide/ext/java/client/refactoring/preview/PreviewPresenterTest.java, plugin-java/che-plugin-java-ext-lang-client/src/test/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/JavaRefactoringRenameTest.java, plugin-java/che-plugin-java-ext-lang-client/src/test/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/RenamePresenterTest.java, plugin-java/che-plugin-java-ext-lang-shared/src/main/java/org/eclipse/che/ide/ext/java/shared/dto/refactoring/ChangeInfo.java, plugin-java/che-plugin-java-ext-lang-shared/src/main/java/org/eclipse/che/ide/ext/java/shared/dto/refactoring/RefactoringResult.java, plugin-java/che-plugin-java-ext-lang-shared/src/main/java/org/eclipse/che/ide/ext/java/shared/dto/refactoring/RefactoringStatus.java
=> IDEX-3089: return the result of applied changes

plugin-angularjs/assembly/pom.xml, plugin-angularjs/pom.xml
Change-Id: I6a179f5d08bcc05ee98420a2b8e0192cdcba1ae1
=> IDEX-3321 Add zip plugin output for AngularJS extensions

plugin-angularjs/README.md, plugin-cpp/README.md, plugin-go/README.md, plugin-php/README.md, plugin-python/README.md, plugin-ruby/README.md, plugin-svn/README.md
Adding a button for plugins that are not packaged by default with Che and that contain only one JAR.
(plugin-angularjs contains several JAR but is already packaged as che-plugin so button uses angularjs-assembly ZIP)
=> IDEX-3333 - adding README with drag&drop button

plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/actions/ExecuteSelectedCommandAction.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/actions/SelectCommandComboBoxReady.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/command/valueproviders/CurrentProjectPathProvider.java
=> IDEX-3279: Fix calculating of current project in multiproject tree.

plugin-docker/che-plugin-docker-client/src/main/java/org/eclipse/che/plugin/docker/client/DockerConnectorConfiguration.java, plugin-docker/che-plugin-docker-client/src/main/java/org/eclipse/che/plugin/docker/client/helper/DefaultNetworkFinder.java, plugin-docker/che-plugin-docker-client/src/main/java/org/eclipse/che/plugin/docker/client/helper/NetworkFinder.java, plugin-docker/che-plugin-docker-client/src/test/java/org/eclipse/che/plugin/docker/client/DockerConnectorConfigurationTest.java, plugin-docker/che-plugin-docker-client/src/test/java/org/eclipse/che/plugin/docker/client/helper/DefaultNetworkFinderHelperTest.java, plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/DockerInstanceProvider.java
Change-Id: I30ceaa9157868f7a6767de22ec3a7e65d97bbb50
=> IDEX-3244 Improve the name of some methods, fix remarks on PR

plugin-docker/che-plugin-docker-client/src/main/java/org/eclipse/che/plugin/docker/client/InitialAuthConfig.java
Change-Id: If25f9da51c8cfb012e099c0bbdee67e4e089257e
=> Replace deprecated call by Guava

plugin-ssh/che-plugin-ssh-git-native/src/main/java/org/eclipse/che/git/impl/nativegit/ssh/SshKeyProviderImpl.java
This reverts commit that reverted removing autogenerating of ssh keys
=> Revert "Revert "IDEX-2234 Removed autogenerating of ssh keys""

plugin-docker/che-plugin-docker-client/src/main/java/org/eclipse/che/plugin/docker/client/DockerConnector.java, plugin-docker/che-plugin-docker-client/src/test/java/org/eclipse/che/plugin/docker/client/DockerConnectorTest.java
Change-Id: I310da371273b56baeef6d1b7f94aa86840bfe1ff
=> Simplify the docker connector by having only one constructor

plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/server/rest/SubversionService.java
It is needed to export config file in svn project.
=> IDEX-2470: Add getImportDescriptor API method for SVN project

plugin-git/che-plugin-git-ext-git/pom.xml, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/GitExtension.java
This i pull request for issue https://jira.codenvycorp.com/browse/IDEX-3164
=> IDEX-3164 : Disable "get project git url" menu item in a temporary workspace

plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/branch/BranchPresenter.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/checkout/CheckoutReferencePresenter.java, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/branch/BranchPresenterTest.java, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/checkout/CheckoutReferenceTest.java
Dependant on Pull request in che-core
codenvy/che-core#368
Signed-off-by: Dror Cohen <dror.cohen@sap.com>
=> Adjust to API changes in Che-core (BranchCheckout -> Checkout)

plugin-git/che-plugin-git-ext-git/pom.xml, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/GitExtension.java
This is pull request into branch 4.0 for issue https://jira.codenvycorp.com/browse/IDEX-3164
=>  IDEX-3164 : Disable "get project git url" menu item in a temporary workspace.

plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/newsourcefile/NewJavaSourceFilePresenter.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/project/node/FQNComparator.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/project/node/PackageNode.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/projecttree/JavaSourceFolderUtil.java
=> Fix render package node element which contains name "java"

plugin-angularjs/core/client/pom.xml, plugin-angularjs/core/client/src/main/resources/org/eclipse/che/plugin/angularjs/core/client/esprima/esprima.js
Change-Id: I693983b609f6056d5266aa9185d75b1cd6998ad4
=> IDEX-3403 Sync esprima version with already approved version with CQ6526

plugin-java/che-plugin-java-ext-jdt/org-eclipse-core-resources/src/main/java/org/eclipse/che/core/internal/resources/Project.java, pom.xml
Reverts codenvy/che-plugins#371
=> Revert aaa2694c372cef51170caf2b316b6574fb9ba749

plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/GitLocalizationConstant.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/importer/page/GitImporterPagePresenter.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/importer/page/GitImporterPageView.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/importer/page/GitImporterPageViewImpl.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/importer/page/GitImporterPageViewImpl.ui.xml, plugin-git/che-plugin-git-ext-git/src/main/resources/org/eclipse/che/ide/ext/git/client/GitLocalizationConstant.properties, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/importer/page/GitImporterPagePresenterTest.java
=> IDEX-3394: Make it possible to set up git branch and use correct sparse checkout

plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/outputspanel/console/CommandOutputConsole.java
=> IDEX-3393: show process error message in the output console of the process

plugin-openshift/che-plugin-openshift-ext-client/src/main/java/org/eclipse/che/ide/ext/openshift/client/OpenshiftLocalizationConstant.java, plugin-openshift/che-plugin-openshift-ext-client/src/main/java/org/eclipse/che/ide/ext/openshift/client/deploy/_new/NewApplicationAction.java, plugin-openshift/che-plugin-openshift-ext-client/src/main/resources/org/eclipse/che/ide/ext/openshift/client/OpenshiftLocalizationConstant.properties
Disable OpenShift deploy for new application if a project is an OpenShift project type
=> IDEX-3513: Disable OpenShift > Deploy > New Application in some case

plugin-openshift/che-plugin-openshift-ext-client/src/main/java/org/eclipse/che/ide/ext/openshift/client/OpenshiftExtension.java, plugin-openshift/che-plugin-openshift-ext-client/src/main/java/org/eclipse/che/ide/ext/openshift/client/OpenshiftLocalizationConstant.java, plugin-openshift/che-plugin-openshift-ext-client/src/main/java/org/eclipse/che/ide/ext/openshift/client/project/UnlinkProjectAction.java, plugin-openshift/che-plugin-openshift-ext-client/src/main/resources/org/eclipse/che/ide/ext/openshift/client/OpenshiftLocalizationConstant.properties
=> IDEX-3376 Add an ability for unlinking a project from Openshift

plugin-orion/che-plugin-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/OrionEditorWidget.java, plugin-orion/che-plugin-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/jso/OrionContentAssistOverlay.java, plugin-orion/che-plugin-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/jso/OrionEditorOverlay.java
=> IDEX-3485: hide JS content assist box after switching to another file

plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/GitLocalizationConstant.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/importer/page/GitImporterPagePresenter.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/importer/page/GitImporterPageView.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/importer/page/GitImporterPageViewImpl.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/importer/page/GitImporterPageViewImpl.ui.xml, plugin-git/che-plugin-git-ext-git/src/main/resources/org/eclipse/che/ide/ext/git/client/GitLocalizationConstant.properties, plugin-github/che-plugin-github-ext-github/src/main/java/org/eclipse/che/ide/ext/github/client/GitHubLocalizationConstant.java, plugin-github/che-plugin-github-ext-github/src/main/java/org/eclipse/che/ide/ext/github/client/importer/page/GithubImporterPagePresenter.java, plugin-github/che-plugin-github-ext-github/src/main/java/org/eclipse/che/ide/ext/github/client/importer/page/GithubImporterPageView.java, plugin-github/che-plugin-github-ext-github/src/main/java/org/eclipse/che/ide/ext/github/client/importer/page/GithubImporterPageViewImpl.java, plugin-github/che-plugin-github-ext-github/src/main/java/org/eclipse/che/ide/ext/github/client/importer/page/GithubImporterPageViewImpl.ui.xml, plugin-github/che-plugin-github-ext-github/src/main/resources/org/eclipse/che/ide/ext/github/client/GitHubLocalizationConstant.properties
We need git clone wirh --recursive to clone multi-module project with submodules.
Will be merged only in 3.x
@vparfonov @skabashnyuk
=> IDEX-2981: Add checkbox for recursive import in import panel

plugin-openshift/che-plugin-openshift-ext-client/src/main/java/org/eclipse/che/ide/ext/openshift/client/project/wizard/CreateProjectWizard.java
Fix closing create project from template Wizard for openShift Projects
=> IDEX-3602: Fix closing create project from template Wizard

plugin-openshift/che-plugin-openshift-ext-client/src/main/java/org/eclipse/che/ide/ext/openshift/client/OpenshiftServiceClient.java, plugin-openshift/che-plugin-openshift-ext-client/src/main/java/org/eclipse/che/ide/ext/openshift/client/OpenshiftServiceClientImpl.java, plugin-openshift/che-plugin-openshift-ext-server/src/main/java/org/eclipse/che/ide/ext/openshift/server/inject/OpenshiftModule.java, plugin-openshift/che-plugin-openshift-ext-server/src/main/java/org/eclipse/che/ide/ext/openshift/server/rest/ReplicationControllerService.java, plugin-openshift/che-plugin-openshift-ext-shared/src/main/java/org/eclipse/che/ide/ext/openshift/shared/dto/ReplicationController.java, plugin-openshift/che-plugin-openshift-ext-shared/src/main/java/org/eclipse/che/ide/ext/openshift/shared/dto/ReplicationControllerSpec.java, plugin-openshift/che-plugin-openshift-ext-shared/src/main/java/org/eclipse/che/ide/ext/openshift/shared/dto/ReplicationControllerStatus.java
=> IDEX-3497 Add API for working with replication controllers

plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/terminal/TerminalPresenter.java
Fix NPE when terminal hasn't connected
=> IDEX-3583. Fix NPE when terminal hasn't connected

plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/outputspanel/console/CommandOutputConsole.java
Fix NPE when performing commands
=> IDEX-3589. Fix NPE when performing commands

plugin-java/che-plugin-java-generator-archetype/src/main/java/org/eclipse/che/generator/archetype/ArchetypeGenerator.java
@vparfonov @azatsarynnyy @skabashnyuk
=> IDEX-3606: fix removing of all projects when ext server stops

plugin-java/che-plugin-java-ext-debugger-java-client/src/main/java/org/eclipse/che/ide/ext/java/jdi/client/JavaRuntimeExtension.java, plugin-java/che-plugin-java-ext-debugger-java-client/src/main/java/org/eclipse/che/ide/ext/java/jdi/client/JavaRuntimeLocalizationConstant.java, plugin-java/che-plugin-java-ext-debugger-java-client/src/main/java/org/eclipse/che/ide/ext/java/jdi/client/actions/ServerLogAction.java, plugin-java/che-plugin-java-ext-debugger-java-client/src/main/resources/org/eclipse/che/ide/ext/java/jdi/client/JavaRuntimeLocalizationConstant.properties, plugin-java/che-plugin-java-ext-debugger-java-client/src/test/java/org/eclipse/che/ide/ext/java/jdi/client/actions/ServerLogActionTest.java
Add ability show log from extension server
=> IDEX-3011 Add ability show log from extension server

plugin-docker/che-plugin-docker-client/src/main/java/org/eclipse/che/plugin/docker/client/DockerConnector.java, plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/DockerInstanceProvider.java, plugin-docker/che-plugin-docker-machine/src/test/java/org/eclipse/che/plugin/docker/machine/DockerInstanceProviderTest.java
@skabashnyuk @evoevodin Please review.
=> IDEX-3660: allow disabling force pull on docker build of machine

plugin-git/che-plugin-git-ext-git/pom.xml
Change-Id: I8461926637975f3906bd47fd66838be79847735a
=> Fix invalid scope of the dependency

plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/server/projecttype/handler/SimpleGeneratorStrategy.java, plugin-java/che-plugin-java-ext-maven/src/test/java/org/eclipse/che/ide/extension/maven/server/projecttype/MavenClassPathConfiguratorTest.java, plugin-java/che-plugin-java-ext-maven/src/test/java/org/eclipse/che/ide/extension/maven/server/projecttype/MavenProjectTypeTest.java, plugin-java/che-plugin-java-ext-maven/src/test/java/org/eclipse/che/ide/extension/maven/server/projecttype/handler/AddMavenModuleHandlerTest.java, plugin-java/che-plugin-java-ext-maven/src/test/java/org/eclipse/che/ide/extension/maven/server/projecttype/handler/MavenProjectImportedTest.java, plugin-java/che-plugin-java-ext-maven/src/test/java/org/eclipse/che/ide/extension/maven/server/projecttype/handler/RemoveMavenModuleHandlerTest.java, plugin-java/che-plugin-java-ext-maven/src/test/java/org/eclipse/che/ide/extension/maven/server/projecttype/handler/SimpleGeneratorStrategyTest.java
=> IDEX-3747: Improve attribute filter. Fix update project with openshift mixin

plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/server/projecttype/handler/AddMavenModuleHandler.java, plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/server/projecttype/handler/RemoveMavenModuleHandler.java, plugin-java/che-plugin-java-ext-maven/src/test/java/org/eclipse/che/ide/extension/maven/server/projecttype/handler/AddMavenModuleHandlerTest.java, plugin-java/che-plugin-java-ext-maven/src/test/java/org/eclipse/che/ide/extension/maven/server/projecttype/handler/RemoveMavenModuleHandlerTest.java
=> IDEX-3631: Fix creating module in project which was cloned with keep directory option.

plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/server/projecttype/MavenProjectResolver.java
=> IDEX-3605: Imported project contains "storage" information

plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/server/projecttype/MavenProjectResolver.java
=> IDEX-3605: Add "storage" information to project

plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/server/projecttype/handler/AddMavenModuleHandler.java
=> IDEX-3631: Add code assistant in created modules

plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/commit/CommitViewImpl.java
Otherwise the focus on the text field wouldn't be settled
@vparfonov please review
=> IDEX-3658: Add delay when setting focus to message field in commit dialog

plugin-angularjs/core/server/src/test/java/org/eclipse/che/plugin/angularjs/core/server/project/type/JSValueProviderFactoryTest.java, plugin-angularjs/core/server/src/test/java/org/eclipse/che/plugin/angularjs/core/server/project/type/grunt/GruntValueProviderFactoryTest.java, plugin-angularjs/core/server/src/test/java/org/eclipse/che/plugin/angularjs/core/server/project/type/gulp/GulpValueProviderFactoryTest.java, plugin-cpp/che-plugin-cpp-ext-cpp/src/test/java/org/eclipse/che/ide/ext/cpp/server/project/type/CPPValueProviderFactoryTest.java, plugin-go/che-plugin-go-ext-go/src/test/java/org/eclipse/che/ide/ext/go/server/project/type/GoValueProviderFactoryTest.java, plugin-java/che-plugin-java-ext-maven/src/test/java/org/eclipse/che/ide/extension/maven/server/projecttype/MavenProjectTypeTest.java, plugin-java/che-plugin-java-ext-maven/src/test/java/org/eclipse/che/ide/extension/maven/server/projecttype/handler/AddMavenModuleHandlerTest.java, plugin-java/che-plugin-java-ext-maven/src/test/java/org/eclipse/che/ide/extension/maven/server/projecttype/handler/MavenProjectImportedTest.java, plugin-java/che-plugin-java-ext-maven/src/test/java/org/eclipse/che/ide/extension/maven/server/projecttype/handler/RemoveMavenModuleHandlerTest.java, plugin-java/che-plugin-java-ext-maven/src/test/java/org/eclipse/che/ide/extension/maven/server/projecttype/handler/SimpleGeneratorStrategyTest.java, plugin-php/che-plugin-php-ext-php/src/test/java/org/eclipse/che/ide/ext/php/server/project/type/PhpValueProviderFactoryTest.java, plugin-python/che-plugin-python-ext-python/src/test/java/org/eclipse/che/ide/ext/python/server/project/type/PythonValueProviderFactoryTest.java, plugin-ruby/che-plugin-ruby-ext-ruby/src/test/java/org/eclipse/che/ide/ext/ruby/server/project/type/RubyValueProviderFactoryTest.java, plugin-svn/che-plugin-svn-ext-subversion/src/test/java/org/eclipse/che/ide/ext/svn/utils/TestUtils.java
This pull request fix tests after change a constructor of the class MemoryFileSystemProvider in this pull request --> https://github.com/codenvy/che-core/pull/459
=> CLDIDE-2656 : Fix tests after change a constructor of the class MemoryFileSystemProvider

plugin-java/che-plugin-java-ext-jdt/che-jdt-ext-machine/src/test/java/org/eclipse/che/ide/ext/java/DummyProjectManager.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/server/SubversionProjectImporter.java, plugin-svn/che-plugin-svn-ext-subversion/src/test/java/org/eclipse/che/ide/ext/svn/server/SubversionProjectImporterTest.java
=> IDEX-3802: Configure project as blank by default after import

plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/client/actions/UpdateDependencyAction.java
=> Activate update dependency action only for maven project type

plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelPresenter.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/ProcessTreeNode.java, plugin-machine/che-plugin-machine-ext-client/src/test/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelPresenterTest.java
Show output of executing command in new panel if current command isn't stopped/finished
Show output of executing command in the same panel if current command is stopped/finished
=> IDEX-3818. Add ability to show output of executing command for several projects

plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/client/MavenExtension.java, plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/client/project/PomNodeInterceptor.java
@vparfonov @skabashnyuk @evidolob 
(http://s38-temporary-files.radikal.ru/f1d3a237b8634fb5b32ce82579f15f17/-929206895.png)
=> Display artifact id as file name for pom.xml files

plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/inject/JavaGinModule.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/project/interceptor/TestContentRootDecorator.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/project/node/jar/AbstractJarEntryNode.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/project/node/jar/JarFileNode.java
Like in IDEA, see screenshots attached below:
@vparfonov @skabashnyuk @ashumilova
=> Mark each Test folder child and Jar child with different background color

plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/server/inject/MavenModule.java, plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/server/projecttype/MavenTargetFilter.java
=> IDEX-3688: add new index filter for the maven target folders

plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/command/CommandConfiguration.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/command/edit/EditCommandResources.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/command/edit/EditCommandsPresenter.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/command/edit/EditCommandsView.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/command/edit/EditCommandsViewImpl.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/command/edit/EditCommandsViewImpl.ui.xml, plugin-machine/che-plugin-machine-ext-client/src/main/resources/org/eclipse/che/ide/extension/machine/client/command/edit/CommandRenderer.css, plugin-machine/che-plugin-machine-ext-client/src/main/resources/org/eclipse/che/ide/extension/machine/client/command/edit/remove-command-button.svg
=> IDEX-3851: command wizard improvements

plugin-java/che-plugin-java-ext-jdt/che-jdt-ext-machine/src/main/java/org/eclipse/che/jdt/rest/JavaClasspathService.java, plugin-java/che-plugin-java-ext-lang-client/pom.xml, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/JavaLocalizationConstant.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/dependenciesupdater/ChannelParameters.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/dependenciesupdater/DependenciesUpdater.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/dependenciesupdater/LogsOutputHandler.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/event/DependencyUpdatedEvent.java, plugin-java/che-plugin-java-ext-lang-client/src/main/resources/org/eclipse/che/ide/ext/java/client/JavaLocalizationConstant.properties, plugin-java/che-plugin-java-ext-lang-client/src/test/java/org/eclipse/che/ide/ext/java/client/dependenciesupdater/LogsOutputHandlerTest.java, plugin-java/che-plugin-java-ext-lang-server/src/main/java/org/eclipse/che/ide/ext/java/server/classpath/ClassPathBuilder.java, plugin-java/che-plugin-java-ext-lang-shared/src/main/java/org/eclipse/che/ide/ext/java/shared/dto/ClassPathBuilderResult.java, plugin-java/che-plugin-java-ext-maven/pom.xml, plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/server/core/BufferOutputFixedRateSender.java, plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/server/core/MavenClassPathBuilder.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/outputspanel/console/DefaultOutputConsole.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/outputspanel/console/OutputConsoleView.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/outputspanel/console/OutputConsoleViewImpl.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/outputspanel/console/OutputConsoleViewImpl.ui.xml, plugin-sdk/che-plugin-sdk-env-local/src/main/java/org/eclipse/che/env/local/server/SingleEnvironmentFilter.java
=> IDEX-3681: Show logs of dependency updater to the output console

plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/MachineResources.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/terminal/TerminalJso.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/terminal/TerminalPresenter.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelPresenter.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelViewImpl.ui.xml, plugin-machine/che-plugin-machine-ext-client/src/main/resources/org/eclipse/che/ide/extension/machine/client/machine.css, plugin-machine/che-plugin-machine-ext-client/src/test/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelPresenterTest.java
Fix behavior of terminal after re-focus
Set focus on terminal after resize
Fix NPE at resizing before terminal is connect
Add ability to select text in processes panel
=> IDEX-3830. Fix behavior of terminal after re-focus

plugin-java/che-plugin-java-ext-debugger-java-client/src/main/java/org/eclipse/che/ide/ext/java/jdi/client/JavaRuntimeLocalizationConstant.java, plugin-java/che-plugin-java-ext-debugger-java-client/src/main/java/org/eclipse/che/ide/ext/java/jdi/client/debug/DebuggerPresenter.java, plugin-java/che-plugin-java-ext-debugger-java-client/src/main/java/org/eclipse/che/ide/ext/java/jdi/client/debug/DebuggerServiceClientImpl.java, plugin-java/che-plugin-java-ext-debugger-java-client/src/main/java/org/eclipse/che/ide/ext/java/jdi/client/debug/remotedebug/RemoteDebugViewImpl.java, plugin-java/che-plugin-java-ext-debugger-java-client/src/main/resources/org/eclipse/che/ide/ext/java/jdi/client/JavaRuntimeLocalizationConstant.properties
@skabashnyuk @vparfonov @tolusha please review
=> IDEX-3887: Do not block IDE when debugger is connecting to remote server

plugin-git/che-plugin-git-ext-git/src/main/resources/org/eclipse/che/ide/ext/git/client/GitLocalizationConstant.properties
=> Fix typos and rename titles in git compare

plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/actions/SelectCommandComboBoxReady.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/command/edit/EditCommandsPresenter.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/command/edit/EditCommandsView.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/command/edit/EditCommandsViewImpl.java
=> IDEX-3914: fix command wizard's selection bug

plugin-github/che-plugin-github-ext-github/src/main/java/org/eclipse/che/ide/ext/github/client/GitHubClientServiceImpl.java, plugin-java/che-plugin-java-ext-debugger-java-client/src/main/java/org/eclipse/che/ide/ext/java/jdi/client/debug/DebuggerServiceClientImpl.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/navigation/filestructure/FileStructurePresenter.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/JavaRefactoringRename.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/search/JavaSearchServiceRest.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/search/JavaSearchServiceWS.java, plugin-java/che-plugin-java-ext-lang-client/src/test/java/org/eclipse/che/ide/ext/java/client/navigation/filestructure/FileStructurePresenterTest.java, plugin-java/che-plugin-java-ext-lang-client/src/test/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/JavaRefactoringRenameTest.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/machine/MachineManagerImpl.java, plugin-ssh/che-plugin-ssh-ext-sshkey/src/main/java/org/eclipse/che/ide/ext/ssh/client/SshKeyServiceImpl.java, plugin-ssh/che-plugin-ssh-ext-sshkey/src/main/java/org/eclipse/che/ide/ext/ssh/client/manage/SshKeyManagerPresenter.java, plugin-ssh/che-plugin-ssh-ext-sshkey/src/test/java/org/eclipse/che/ide/ext/ssh/client/manage/SshKeyManagerPresenterTest.java, plugin-svn/che-plugin-svn-ext-subversion/src/main/java/org/eclipse/che/ide/ext/svn/client/SubversionClientServiceImpl.java
New loaders has new style. For more info look screenshots attached below.
@slemeur
=> IDEX-3905: Change the general loader

plugin-gwt/che-plugin-gwt-ext-gwt/pom.xml, plugin-gwt/che-plugin-gwt-ext-gwt/src/main/java/org/eclipse/che/ide/ext/gwt/server/GwtModule.java, plugin-gwt/che-plugin-gwt-ext-gwt/src/main/java/org/eclipse/che/ide/ext/gwt/server/GwtProjectType.java, plugin-java/che-plugin-java-ext-lang-server/pom.xml, plugin-java/che-plugin-java-ext-lang-server/src/main/java/org/eclipse/che/ide/ext/java/server/inject/JavaModule.java, plugin-java/che-plugin-java-ext-lang-server/src/main/java/org/eclipse/che/ide/ext/java/server/projecttype/JavaProjectType.java, plugin-java/che-plugin-java-ext-lang-server/src/main/java/org/eclipse/che/ide/ext/java/server/projecttype/JavaPropertiesValueProviderFactory.java, plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/server/inject/MavenModule.java, plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/server/projecttype/MavenProjectType.java, plugin-java/che-plugin-java-ext-maven/src/test/java/org/eclipse/che/ide/extension/maven/server/projecttype/MavenClassPathConfiguratorTest.java, plugin-java/che-plugin-java-ext-maven/src/test/java/org/eclipse/che/ide/extension/maven/server/projecttype/MavenProjectTypeTest.java, plugin-java/che-plugin-java-ext-maven/src/test/java/org/eclipse/che/ide/extension/maven/server/projecttype/handler/AddMavenModuleHandlerTest.java, plugin-java/che-plugin-java-ext-maven/src/test/java/org/eclipse/che/ide/extension/maven/server/projecttype/handler/MavenProjectImportedTest.java, plugin-java/che-plugin-java-ext-maven/src/test/java/org/eclipse/che/ide/extension/maven/server/projecttype/handler/RemoveMavenModuleHandlerTest.java, plugin-java/che-plugin-java-ext-maven/src/test/java/org/eclipse/che/ide/extension/maven/server/projecttype/handler/SimpleGeneratorStrategyTest.java, plugin-svn/che-plugin-svn-ext-subversion/src/test/java/org/eclipse/che/ide/ext/svn/server/SubversionProjectImporterTest.java
Project Type framework was reworked to simplify its using
All the tests of core and plugins are passed, IDE started as well
=> Project Type framework refactoring

plugin-github/che-plugin-github-ext-github/src/main/java/org/eclipse/che/ide/ext/github/client/GitHubLocalizationConstant.java, plugin-github/che-plugin-github-ext-github/src/main/java/org/eclipse/che/ide/ext/github/client/GitHubSshKeyProvider.java, plugin-github/che-plugin-github-ext-github/src/main/java/org/eclipse/che/ide/ext/github/client/authenticator/GitHubAuthenticatorImpl.java, plugin-github/che-plugin-github-ext-github/src/main/java/org/eclipse/che/ide/ext/github/client/authenticator/GitHubAuthenticatorViewImpl.java, plugin-github/che-plugin-github-ext-github/src/main/resources/org/eclipse/che/ide/ext/github/client/GitHubLocalizationConstant.properties
Handled "onCancel" action in ask to authorize on GitHub dialog when generating SSH keys. Changed title and text in that dialog.
@skabashnyuk @vparfonov please review
=> IDEX-3842: Fix generating ssh keys when user rejected GitHub authorization

plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/MachineLocalizationConstant.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/MachineResources.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelPresenter.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelView.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelViewImpl.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/ProcessTreeRenderer.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/StopProcessHandler.java, plugin-machine/che-plugin-machine-ext-client/src/main/resources/org/eclipse/che/ide/extension/machine/client/MachineLocalizationConstant.properties, plugin-machine/che-plugin-machine-ext-client/src/main/resources/org/eclipse/che/ide/extension/machine/client/machine.css, plugin-machine/che-plugin-machine-ext-client/src/test/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelPresenterTest.java
Add button to stop specific process without closing its output
=> IDEX-3947 Add button to stop specific process without closing its output

plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/local/LocalDockerModule.java, plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/local/node/provider/LocalWorkspaceFolderPathProvider.java, plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/local/provider/CheHostVfsRootDirProvider.java, plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/node/WorkspaceFolderPathProvider.java, plugin-docker/che-plugin-docker-machine/src/test/java/org/eclipse/che/plugin/docker/machine/local/node/provider/LocalWorkspaceFolderPathProviderTest.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/machine/MachineManagerImpl.java
It will be useful for internal use. By default all workpace will locate in che.host.fs_root_dir dir by ws-name
=> Add special property for projects from your host

plugin-docker/che-plugin-docker-machine/pom.xml
Change-Id: I7fc7f4f8fdb2352f189448cfe9aef3ca4285b601
=> Fix dependency

plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/DockerInstance.java, plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/DockerMachineFactory.java, plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/DockerProcess.java, plugin-docker/che-plugin-docker-machine/src/test/java/org/eclipse/che/plugin/docker/machine/integration/DockerProcessTest.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/MachineLocalizationConstant.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/command/CommandManager.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelPresenter.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/ProcessTreeNode.java, plugin-machine/che-plugin-machine-ext-client/src/main/resources/org/eclipse/che/ide/extension/machine/client/MachineLocalizationConstant.properties, plugin-machine/che-plugin-machine-ext-client/src/test/java/org/eclipse/che/ide/extension/machine/client/command/CommandManagerTest.java, plugin-machine/che-plugin-machine-ext-client/src/test/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelPresenterTest.java
Restore processes panes after page refreshing
=> IDEX-3929. Restore processes panes after page refreshing

plugin-java/che-plugin-java-ext-jdt/che-jdt-ext-machine/src/test/java/org/eclipse/che/ide/ext/java/DummyProjectManager.java
=> IDEX-3991: Synchronize workspace master and VFS

plugin-machine/che-plugin-machine-ext-server/pom.xml
Change-Id: Ibd5bf304aa71f5d1318a0b6effb165e26dd350a0
=> Fix dependency scope

plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/GitRepositoryInitializer.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/branch/BranchPresenter.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/remote/RemotePresenter.java, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/branch/BranchPresenterTest.java, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/remote/RemotePresenterTest.java, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/utils/GitRepositoryInitializerTest.java
@vparfonov @skabashnyuk @sleshchenko please review
=> IDEX-3576: refresh git project attributes when performing related operations

plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/MachinePerspective.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/machine/panel/MachinePanelPresenter.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/recipe/editor/RecipeFileFactory.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/recipe/entry/RecipeWidget.ui.xml, plugin-machine/che-plugin-machine-ext-client/src/test/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/machine/panel/MachinePanelPresenterTest.java, plugin-machine/che-plugin-machine-ext-client/src/test/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/recipe/editor/RecipeFileFactoryTest.java
Display the panel for managing recipes regardless of whether a project exists in workspace
Fix bug related with incorrect displaying recipes after switch between perspectives
Fix displaying list of recipes(css).
=> IDEX-3896. Display the panel for managing recipes regardless of whether a project exists in workspace

plugin-java/che-plugin-java-ext-maven/pom.xml
=> add missing dependency

plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/MachineLocalizationConstant.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/MachineResources.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/outputspanel/console/DefaultOutputConsole.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelPresenter.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelView.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelViewImpl.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/PreviewSshClickHandler.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/ProcessTreeRenderer.java, plugin-machine/che-plugin-machine-ext-client/src/main/resources/org/eclipse/che/ide/extension/machine/client/MachineLocalizationConstant.properties, plugin-machine/che-plugin-machine-ext-client/src/main/resources/org/eclipse/che/ide/extension/machine/client/machine.css
@vparfonov @ashumilova @slemeur
=> IDEX-3768: Add ssh widget to console panel

plugin-machine/che-plugin-machine-ext-client/src/main/resources/org/eclipse/che/ide/extension/machine/client/machine.css
Result on Dark Theme
Result on Light Theme
=> IDEX-4025: Change color of the stop button in console

plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/WindowsHostUtils.java, plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ext/provider/DockerExtConfBindingProvider.java, plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ext/provider/ExtServerVolumeProvider.java, plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/ext/provider/TerminalVolumeProvider.java, plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/local/provider/CheHostVfsRootDirProvider.java, plugin-docker/che-plugin-docker-machine/src/test/java/org/eclipse/che/plugin/docker/machine/local/node/provider/LocalWorkspaceFolderPathProviderTest.java
Copy terminal,ws-agent and ext-config to the Windows User Home need for mountig this directory to the docker container
=> Che on Windows - copy ws-agent from che.properties location.

plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/JavaLocalizationConstant.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/move/wizard/MovePresenter.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/RenamePresenter.java, plugin-java/che-plugin-java-ext-lang-client/src/main/resources/org/eclipse/che/ide/ext/java/client/JavaLocalizationConstant.properties, plugin-java/che-plugin-java-ext-lang-client/src/test/java/org/eclipse/che/ide/ext/java/client/refactoring/move/wizard/MovePresenterTest.java, plugin-java/che-plugin-java-ext-lang-client/src/test/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/RenamePresenterTest.java
=> IDEX-3617: Add loader when code refactoring takes a lot of time

plugin-orion/che-plugin-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/OrionEditorWidget.java, plugin-orion/che-plugin-orion-editor/src/main/java/org/eclipse/che/ide/editor/orion/client/jso/OrionEditorViewOverlay.java
=> Fix applying Orion editor's settings

plugin-java/che-plugin-java-ext-debugger-java-client/src/main/java/org/eclipse/che/ide/ext/java/jdi/client/JavaRuntimeLocalizationConstant.java, plugin-java/che-plugin-java-ext-debugger-java-client/src/main/java/org/eclipse/che/ide/ext/java/jdi/client/debug/remotedebug/RemoteDebugViewImpl.ui.xml, plugin-java/che-plugin-java-ext-debugger-java-client/src/main/resources/org/eclipse/che/ide/ext/java/jdi/client/JavaRuntimeLocalizationConstant.properties
@tolusha, @skabashnyuk please review this pull request.
=> IDEX-4038: add description to remote debug view

plugin-github/che-plugin-github-oauth2/pom.xml, plugin-github/che-plugin-github-oauth2/src/main/java/org/eclipse/che/security/oauth/GitHubOAuthAuthenticator.java
@skabashnyuk Please review my changes
=> CLDIDE-2561 Make configuring of GitHubOAuthAuthenticator optional

plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/RenamePresenter.java
=> IDEX-3617: Fix hiding loader when apply inadmissible rename

plugin-docker/che-plugin-docker-machine/pom.xml, plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/local/node/provider/LocalWorkspaceFolderPathProvider.java, plugin-docker/che-plugin-docker-machine/src/test/java/org/eclipse/che/plugin/docker/machine/local/node/provider/LocalWorkspaceFolderPathProviderTest.java
=> User WS name instead WS ID for root projects folder

plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/MachineResources.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/command/CommandManager.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/outputspanel/console/CommandOutputConsole.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/outputspanel/console/DefaultOutputConsole.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/outputspanel/console/OutputConsole.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelPresenter.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelView.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelViewImpl.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/event/ProcessFinishedEvent.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/event/ProcessFinishedHandler.java, plugin-machine/che-plugin-machine-ext-client/src/main/resources/org/eclipse/che/ide/extension/machine/client/machine.css, plugin-machine/che-plugin-machine-ext-client/src/test/java/org/eclipse/che/ide/extension/machine/client/command/CommandManagerTest.java, plugin-machine/che-plugin-machine-ext-client/src/test/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelPresenterTest.java
=> IDEX-4045: Hide 'stop process' button when process has finished

plugin-java/che-plugin-java-ext-jdt/che-jdt-ext-machine/src/test/java/org/eclipse/che/jdt/refactoring/RenameRefactoringTest.java, plugin-java/che-plugin-java-ext-jdt/org-eclipse-core-resources/src/main/java/org/eclipse/che/core/internal/resources/Resource.java, plugin-java/che-plugin-java-ext-jdt/org-eclipse-jdt-ui/src/main/java/org/eclipse/ui/editors/text/templates/ContributionTemplateStore.java
We get all project from workspace found project by path of resources by select longest path of project that match current resource path
=> IDEX-4106: fix problem with founding project by full resource path.

plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/RenamePresenter.java
=> Allow refactoring if we get WARNING in changes

plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/RefactoringUpdater.java
Correct updating children of source folder after rename refactoring
Setup selection in project tree on removed node parent after removing the last ones
@vparfonov
=> IDEX-4136: Rename refactoring java class fails

plugin-machine/che-plugin-machine-ext-client/src/main/resources/org/eclipse/che/ide/extension/machine/client/machine.css
Fixup! Changed text color of DEV machine label
=> IDEX-4029 Improve the styles for the light theme in console panel

plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/JavaLocalizationConstant.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/navigation/service/JavaNavigationServiceImpl.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/RefactoringUpdater.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/move/wizard/MovePresenter.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/RenamePresenter.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/service/RefactoringServiceClientImpl.java, plugin-java/che-plugin-java-ext-lang-client/src/main/resources/org/eclipse/che/ide/ext/java/client/JavaLocalizationConstant.properties, plugin-java/che-plugin-java-ext-lang-client/src/test/java/org/eclipse/che/ide/ext/java/client/refactoring/move/wizard/MovePresenterTest.java, plugin-java/che-plugin-java-ext-lang-client/src/test/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/RenamePresenterTest.java
=> IDEX-4131: Improve refactoring wizard dialog in case we got WARNING in severity

plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/editor/JavaCodeAssistProcessor.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/editor/JavaCompletionProposal.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/editor/JavaQuickAssistProcessor.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/RefactoringUpdater.java
=> IDEX-4172: fix problems with Move refactoring

plugin-java/che-plugin-java-ext-jdt/org-eclipse-jdt-ui/src/main/java/org/eclipse/ui/editors/text/templates/ContributionTemplateStore.java
=> IDEX-4162: fix a path to template resources

plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/widgets/recipe/editor/RecipeFileFactory.java
Turn on syntax highlighting in recipe editor on 'Recipes' panel (Machine perspective)
@vparfonov
=> Turn on syntax highlighting in recipe editor on 'Recipes' panel (Machine perspective)

plugin-java/che-plugin-java-ext-maven/src/main/java/org/eclipse/che/ide/extension/maven/server/projecttype/MavenProjectResolver.java
Add rename project feature.
@vparfonov
=> IDEX-4155: Add ability to rename project via Project wizard.

plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/RenamePresenter.java, plugin-java/che-plugin-java-ext-lang-client/src/test/java/org/eclipse/che/ide/ext/java/client/refactoring/rename/wizard/RenamePresenterTest.java
=> IDEX-3996: Fix bug related to renaming class from project explorer

plugin-orion/che-plugin-orion-compare/src/main/resources/org/eclipse/che/ide/orion/public/Compare.html
=> IDEX-3934: Set splitter position to middle in Compare widget on first load

plugin-bower/pom.xml, plugin-docker/che-plugin-docker-client/pom.xml, plugin-docker/che-plugin-docker-ext-client/pom.xml, plugin-docker/che-plugin-docker-machine/pom.xml, plugin-git/che-plugin-git-ssh-client/pom.xml, plugin-grunt/pom.xml, plugin-gulp/pom.xml, plugin-java/che-plugin-java-ext-debugger-java-shared/pom.xml, plugin-java/che-plugin-java-ext-jdt/che-plugin-java-jdt-core-repack/pom.xml, plugin-java/che-plugin-java-ext-jdt/org-eclipse-core-filesystem/pom.xml, plugin-java/che-plugin-java-ext-jdt/org-eclipse-core-resources/pom.xml, plugin-java/che-plugin-java-ext-jdt/org-eclipse-jface/pom.xml, plugin-java/che-plugin-java-ext-lang-server/pom.xml, plugin-java/che-plugin-java-ext-lang-shared/pom.xml, plugin-java/che-plugin-java-generator-archetype/pom.xml, plugin-java/che-plugin-java-maven-tools/pom.xml, plugin-machine/che-plugin-machine-ext-client/pom.xml, plugin-machine/che-plugin-machine-ssh-client/pom.xml, plugin-orion/che-plugin-orion-compare/pom.xml, plugin-orion/che-plugin-orion-editor/pom.xml, plugin-sdk/che-plugin-sdk-env-local/pom.xml, plugin-svn/che-plugin-svn-ext-subversion/pom.xml, plugin-web/che-plugin-web-ext-web/pom.xml, plugin-yeoman/pom.xml
Disable findbugs build fail in modiles that fails if
enable it by default
@skabashnyuk @vparfonov
=> Disable fail build by findbugs

plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/GitExtension.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/GitLocalizationConstant.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/action/CompareWithLatestAction.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/action/CompareWithRevisionAction.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/commit/CommitPresenter.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/compare/CompareViewImpl.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/compare/CompareViewImpl.ui.xml, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/compare/branchList/BranchListPresenter.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/compare/branchList/BranchListViewImpl.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/compare/changedList/ChangedListViewImpl.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/compare/changedList/ChangedListViewImpl.ui.xml, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/compare/revisionsList/RevisionListPresenter.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/compare/revisionsList/RevisionListView.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/compare/revisionsList/RevisionListViewImpl.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/compare/revisionsList/RevisionListViewImpl.ui.xml, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/history/HistoryPresenter.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/inject/GitGinModule.java, plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/reset/commit/ResetToCommitPresenter.java, plugin-git/che-plugin-git-ext-git/src/main/resources/org/eclipse/che/ide/ext/git/client/GitLocalizationConstant.properties, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/history/HistoryPresenterTest.java, plugin-git/che-plugin-git-ext-git/src/test/java/org/eclipse/che/ide/ext/git/client/reset/commit/ResetToCommitPresenterTest.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/preview/PreviewViewImpl.java, plugin-orion/che-plugin-orion-compare/src/main/java/org/eclipse/che/ide/orion/compare/CompareWidget.java, plugin-orion/che-plugin-orion-compare/src/main/resources/org/eclipse/che/ide/orion/public/Compare.html
@vparfonov  @skabashnyuk please review
=> IDEX-3928: Add Compare with revision functionality

plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/refactoring/RefactoringUpdater.java
=> IDEX-4164: fix potential npe

plugin-java/che-plugin-java-ext-jdt/org-eclipse-jdt-ui/src/main/java/org/eclipse/jdt/internal/core/DeltaProcessor.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/editor/JavaAnnotationModel.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/editor/JavaReconcilerStrategy.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/editor/JsJavaEditorConfiguration.java, plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/editor/ProblemRequester.java
In DeltaProcessor we make hard fix:
we remove cache for all projects (not only for deleted) its not right way but working well for now
=> Clean cache after deleteing project. Code clean up

plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/search/FindUsagesViewImpl.java
=> IDEX-4161: Fix focus on 'Usages' panel after calling 'Find Usages' feature

plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelViewImpl.java
Add ability to test closing of Consoles panel by selenium tests
=> Add ability to test closing of Consoles panel by selenium tests

plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelPresenter.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelView.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelViewImpl.java, plugin-machine/che-plugin-machine-ext-client/src/test/java/org/eclipse/che/ide/extension/machine/client/processes/ConsolesPanelPresenterTest.java
Fix incorrect state stop process button
Fix duplicate set active part
=> Fix incorrect state stop process button

plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/DockerInstanceProvider.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/machine/MachineManagerImpl.java
- memorySize -> ram
- Change "script" variable name to "recipe".
=> Rename emvironment model parameter names

plugin-orion/che-plugin-orion-editor/src/main/resources/org/eclipse/che/ide/editor/orion/client/orion-codenvy-theme.css
@slemeur  @ashumilova  @vparfonov
=> IDEX-4159. Improve styles for search blocks

plugin-orion/che-plugin-orion-compare/src/main/resources/org/eclipse/che/ide/orion/public/built-compare-codenvy.css, plugin-orion/che-plugin-orion-compare/src/main/resources/org/eclipse/che/ide/orion/public/built-compare-dark-codenvy.css
=> IDEX-4082: Better style compare widget

plugin-git/che-plugin-git-ext-git/src/main/java/org/eclipse/che/ide/ext/git/client/remove/RemoveFromIndexPresenter.java
=> IDEX-3531: Item is removed from project tree after remove from index

plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/perspective/MachinePerspective.java, plugin-machine/che-plugin-machine-ext-client/src/test/java/org/eclipse/che/ide/extension/machine/client/perspective/MachinePerspectiveTest.java
=> IDEX-3779: Fix reset cursor position in editor after switching perspective

plugin-java/che-plugin-java-ext-lang-client/src/main/java/org/eclipse/che/ide/ext/java/client/dependenciesupdater/LogsOutputHandler.java, plugin-machine/che-plugin-machine-ext-client/src/main/java/org/eclipse/che/ide/extension/machine/client/machine/MachineManagerImpl.java
=> IDEX-4111: Fix showing several messages "Workspace agent started".
